/*
 * Copyright Stalwart Labs LLC See the COPYING
 * file at the top-level directory of this distribution.
 *
 * Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
 * https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
 * <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
 * option. This file may not be copied, modified, or distributed
 * except according to those terms.
 */

//! ContactCard wraps a JSContact Card (RFC 9553) object.
//!
//! Unlike Email or Mailbox, a ContactCard IS a JSContact object — its
//! property set is open-ended and includes vendor extension properties.
//! The struct therefore stores all properties in a `serde_json::Map`
//! for round-trip fidelity.
//!
//! Typed accessor and builder methods are provided for common properties.
//! For extension or less-common properties, use [`ContactCard::property()`]
//! and [`ContactCard::set_property()`].
//!
//! For vCard ↔ JSContact conversion, the `calcard` crate (re-exported
//! from this crate) can parse the serialized JSON.

pub mod get;
pub mod helpers;
pub mod parse;
pub mod query;
pub mod set;

crate::json_object_struct!(ContactCard, "a JSContact object", Property, ());

// ---- Property enum ----

crate::define_open_property_enum! {
    /// Property names for ContactCard/get `properties` lists.
    ///
    /// Common JSContact properties have typed variants. Extension or
    /// less-common properties use `Other(String)`.
    #[non_exhaustive]
    pub enum Property {
        Id => "id",
        Uid => "uid",
        AddressBookIds => "addressBookIds",
        Kind => "kind",
        Name => "name",
        Nicknames => "nicknames",
        Emails => "emails",
        Phones => "phones",
        Addresses => "addresses",
        Organizations => "organizations",
        OnlineServices => "onlineServices",
        Notes => "notes",
        Media => "media",
        Created => "created",
        /// Any JSContact property not covered by the typed variants,
        /// including vendor extension properties.
        Updated => "updated",
    }
}

// Object, ChangesObject, and SetObject impls generated by json_object_struct! macro.

use crate::{Get, Set};

// Method structs for the new architecture
crate::define_get_method!(ContactCardGet, ContactCard<Set>, "ContactCard/get", crate::core::capability::Contacts, crate::core::get::GetResponse<ContactCard<Get>>);
crate::define_set_method!(ContactCardSet, ContactCard<Set>, "ContactCard/set", crate::core::capability::Contacts, crate::core::set::SetResponse<ContactCard<Get>>);
crate::define_changes_method!(ContactCardChanges, "ContactCard/changes", crate::core::capability::Contacts, crate::core::changes::ChangesResponse<ContactCard<Get>>);
crate::define_query_method!(ContactCardQuery, ContactCard<Set>, "ContactCard/query", crate::core::capability::Contacts);
crate::define_query_changes_method!(ContactCardQueryChanges, ContactCard<Set>, "ContactCard/queryChanges", crate::core::capability::Contacts);
crate::define_copy_method!(ContactCardCopy, ContactCard<Set>, "ContactCard/copy", crate::core::capability::Contacts, crate::core::copy::CopyResponse<ContactCard<Get>>);
